packages:
  - "apps/*"
  - "packages/*"
overrides:
  deepmerge-ts: ^8.0.0
  source-map-js: ^1.2.2
allowBuilds:
  "@prisma/client": true
  "@prisma/engines": true
  argon2: true
  esbuild: true
  prisma: true
